sources:
  - name: main
    tables:
      - name: bike_data
        columns:
          - name: tripduration
            data_type: CHARACTER VARYING(256)
          - name: starttime
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: stoptime
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: start station id
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: start station name
            data_type: CHARACTER VARYING(256)
          - name: start station latitude
            data_type: CHARACTER VARYING(256)
          - name: start station longitude
            data_type: CHARACTER VARYING(256)
          - name: end station id
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: end station name
            data_type: CHARACTER VARYING(256)
          - name: end station latitude
            data_type: CHARACTER VARYING(256)
          - name: end station longitude
            data_type: CHARACTER VARYING(256)
          - name: bikeid
            data_type: CHARACTER VARYING(256)
          - name: usertype
            data_type: CHARACTER VARYING(256)
          - name: birth year
            data_type: CHARACTER VARYING(256)
          - name: gender
            data_type: CHARACTER VARYING(256)
          - name: ride_id
            data_type: CHARACTER VARYING(256)
          - name: rideable_type
            data_type: CHARACTER VARYING(256)
          - name: started_at
            data_type: CHARACTER VARYING(256)
          - name: ended_at
            data_type: CHARACTER VARYING(256)
          - name: start_station_name
            data_type: CHARACTER VARYING(256)
          - name: start_station_id
            data_type: CHARACTER VARYING(256)
          - name: end_station_name
            data_type: CHARACTER VARYING(256)
          - name: end_station_id
            data_type: CHARACTER VARYING(256)
          - name: start_lat
            data_type: CHARACTER VARYING(256)
          - name: start_lng
            data_type: CHARACTER VARYING(256)
          - name: end_lat
            data_type: CHARACTER VARYING(256)
          - name: end_lng
            data_type: CHARACTER VARYING(256)
          - name: member_casual
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)


      - name: central_park_weather
        columns:
          - name: station
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
          - name: name
            data_type: CHARACTER VARYING(256)
          - name: date
            data_type: CHARACTER VARYING(256)
          - name: awnd
            data_type: CHARACTER VARYING(256)
            description: "Average wind speed"
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: prcp
            data_type: CHARACTER VARYING(256)
            description: "Precipitation"
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: snow
            data_type: CHARACTER VARYING(256)
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: snwd
            data_type: CHARACTER VARYING(256)
            description: "PSnow depth"
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: tmax
            data_type: CHARACTER VARYING(256)
          - name: tmin
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_bases
        columns:
          - name: base_number
            data_type: CHARACTER VARYING(256)
            description: "The TLC license number of the dispatching base"
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: base_name
            data_type: CHARACTER VARYING(256)
            description: "The official name of the base entity"
          - name: dba
            data_type: CHARACTER VARYING(256)
          - name: dba_category
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_tripdata
        columns:
          - name: dispatching_base_num
            data_type: CHARACTER VARYING(256)
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  to : source('main','fhv_bases')
                  field: base_number
                  severity: WARN
          - name: pickup_datetime
            data_type: TIMESTAMP
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: dropoff_datetime
            data_type: TIMESTAMP
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: pulocationid
            data_type: DOUBLE
            description: "TLC Taxi Zone in which the trip began"
          - name: dolocationid
            data_type: DOUBLE
          - name: sr_flag
            data_type: INTEGER
            description: " For shared trips, the value is 1. For non-shared rides, this field is null."
          - name: affiliated_base_number
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhvhv_tripdata
        columns:
          - name: hvfhs_license_num
            data_type: CHARACTER VARYING(256)
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - accepted_values:
                  values: ['HV0002', 'HV0003', 'HV0004', 'HV0005']  
          - name: dispatching_base_num
            data_type: CHARACTER VARYING(256)
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  to : source('main','fhv_bases')
                  field: base_number
                  severity: WARN
          - name: originating_base_num
            data_type: CHARACTER VARYING(256)
          - name: request_datetime
            data_type: TIMESTAMP
          - name: on_scene_datetime
            data_type: TIMESTAMP
          - name: pickup_datetime
            data_type: TIMESTAMP
          - name: dropoff_datetime
            data_type: TIMESTAMP
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: trip_miles
            data_type: DOUBLE
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
                  max_value: 10000
          - name: trip_time
            data_type: BIGINT
          - name: base_passenger_fare
            data_type: DOUBLE
          - name: tolls
            data_type: DOUBLE
          - name: bcf
            data_type: DOUBLE
          - name: sales_tax
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: airport_fee
            data_type: DOUBLE
          - name: tips
            data_type: DOUBLE
          - name: driver_pay
            data_type: DOUBLE
          - name: shared_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger agree to a shared/pooled ride"
          - name: shared_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger share the vehicle with another passenger who booked separately at any point during the trip?"
          - name: access_a_ride_flag
            data_type: CHARACTER VARYING(256)
            description: "Was the trip administered on behalf of the Metropolitan Transportation Authority"
          - name: wav_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger request a wheelchair-accessible vehicle "
          - name: wav_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the trip occur in a wheelchair-accessible vehicle"
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: green_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
          - name: lpep_pickup_datetime
            data_type: TIMESTAMP
          - name: lpep_dropoff_datetime
            data_type: TIMESTAMP
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
          - name: ratecodeid
            data_type: DOUBLE
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: passenger_count
            data_type: DOUBLE
          - name: trip_distance
            data_type: DOUBLE
          - name: fare_amount
            data_type: DOUBLE
          - name: extra
            data_type: DOUBLE
          - name: mta_tax
            data_type: DOUBLE
          - name: tip_amount
            data_type: DOUBLE
          - name: tolls_amount
            data_type: DOUBLE
          - name: ehail_fee
            data_type: INTEGER
          - name: improvement_surcharge
            data_type: DOUBLE
          - name: total_amount
            data_type: DOUBLE
          - name: payment_type
            data_type: DOUBLE
          - name: trip_type
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: yellow_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
          - name: tpep_pickup_datetime
            data_type: TIMESTAMP
          - name: tpep_dropoff_datetime
            data_type: TIMESTAMP
          - name: passenger_count
            data_type: DOUBLE
          - name: trip_distance
            data_type: DOUBLE
          - name: ratecodeid
            data_type: DOUBLE
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: payment_type
            data_type: BIGINT
          - name: fare_amount
            data_type: DOUBLE
          - name: extra
            data_type: DOUBLE
          - name: mta_tax
            data_type: DOUBLE
          - name: tip_amount
            data_type: DOUBLE
          - name: tolls_amount
            data_type: DOUBLE
          - name: improvement_surcharge
            data_type: DOUBLE
          - name: total_amount
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: airport_fee
            data_type: DOUBLE
          - name: filename
            data_type: CHARACTER VARYING(256)
